version: '3.9'

services:
  backend:
    build: ./planflow_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./planflow_backend:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./planflow_backend/.env
